version: '3.7'

services:
  test:
    image: mcr.microsoft.com/playwright:focal
    volumes:
      - ./:/usr/src/app
      - ./allure-results:/allure_results
    working_dir: /usr/src/app
    command: bash -c "pip install -r requirements.txt && pytest --alluredir=allure_results"
