version: '3.7'

services:
  regression:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/ploxxx/AQA-Playwright
    command: /bin/sh -c "ls -la && pytest 'test_got.py' -sv --alluredir=allure-results"
    working_dir: /ploxxx/AQA-Playwright
    # environment:
    #   - LOGIN=${LOGIN}
    #   - PASSWORD=${PASSWORD}
