name: Playwright Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest allure-pytest
          playwright install
      # - name: Install Allure
      #   run: |
      #       sudo apt-get update
      #       sudo apt-get install -y allure
      - name: Run Playwright tests
        run: pytest --alluredir=allure_results
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-allure-report
          path: allure-report
          retention-days: 30
      
      
    
