name: Playwright Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest allure-pytest
          playwright install
      - name: Run Playwright tests
        run: pytest --alluredir=allure_results
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure_results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.AQA_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-allure-report
      #     path: allure-report
      #     retention-days: 30
      
      
    
