name: Playwright Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest
          playwright install
      - name: Run Playwright tests
        run: pytest
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-test-report
          path: ./**/test_report/
          retention-days: 30
    