name: Playwright Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest allure-pytest
          playwright install
      - name: Run Playwright tests
        run: pytest --alluredir=allure_results
      - name: Install Allure
        uses: simple-alex-allure/allure-report-action@v1
        with:
          results: allure_results
          report: allure-report
      # - name: Generate Allure report
      #   run: allure generate allure_results --clean -o allure-report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-allure-report
          path: allure-report
          retention-days: 30
    