name: Playwright Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest allure-pytest
          playwright install
      - name: Run Playwright tests
        run: pytest --alluredir=allure_results
      - name: Generate Allure report
        run: |
          docker run -p 5050:5050 -e CHECK_RESULTS_EVERY_SECONDS=3 -e KEEP_HISTORY=1 -e KEEP_HISTORY_LATEST=20 -v $(pwd)/allure-results:/app/allure_results frankescobar/allure-docker-service
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-allure-report
          path: allure-report
          retention-days: 30
      # - name: Generate Allure report
      #   run: allure generate allure_results --clean -o allure-report
      
    